version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "mb"
      POSTGRES_USER: "mb"
      POSTGRES_DB: "mb-api-dev"
    ports:
      - "15430:5431"
    networks:
      - mb-backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@postgres.br"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "1654:80"
    networks:
      - mb-backend

  mb-api:
    image: node:13-alpine
    working_dir: "/home/api"
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./:/home/api
      - /home/api/node_modules
    networks:
      - mb-backend
    command: >
      sh -c "yarn &&
      yarn base:init &&
      yarn start:dev &&
      yarn cache clean"

networks:
  mb-backend:
    driver: bridge
